-- CreateTable
CREATE TABLE "Campaign" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,

    CONSTRAINT "Campaign_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Recording" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "callTime" TIMESTAMP(3) NOT NULL,
    "phoneNumber" STRING NOT NULL,
    "campaignId" INT4 NOT NULL,
    "agentId" INT4 NOT NULL,
    "volunteerNumber" INT4 NOT NULL,
    "recording" STRING NOT NULL,

    CONSTRAINT "Recording_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Recording" ADD CONSTRAINT "Recording_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
